# ─────────────────────────────────────────────────────────────
#  Generado por Sat.Catalogos.Codegen — NO EDITAR.
#  Source: packages/files/4.0/catCFDI.xsd + catCFDI.xlsx
# ─────────────────────────────────────────────────────────────
defmodule Sat.Catalogos.Pais do
  @moduledoc "Catálogo c_Pais del SAT (CFDI 4.0)."

  @type t :: %{value: String.t(), label: String.t(), deprecated: boolean()}

  @entries [
    %{value: "AFG", label: "Afganistán", deprecated: false},
    %{value: "ALA", label: "Islas Åland", deprecated: false},
    %{value: "ALB", label: "Albania", deprecated: false},
    %{value: "DEU", label: "Alemania", deprecated: false},
    %{value: "AND", label: "Andorra", deprecated: false},
    %{value: "AGO", label: "Angola", deprecated: false},
    %{value: "AIA", label: "Anguila", deprecated: false},
    %{value: "ATA", label: "Antártida", deprecated: false},
    %{value: "ATG", label: "Antigua y Barbuda", deprecated: false},
    %{value: "SAU", label: "Arabia Saudita", deprecated: false},
    %{value: "DZA", label: "Argelia", deprecated: false},
    %{value: "ARG", label: "Argentina", deprecated: false},
    %{value: "ARM", label: "Armenia", deprecated: false},
    %{value: "ABW", label: "Aruba", deprecated: false},
    %{value: "AUS", label: "Australia", deprecated: false},
    %{value: "AUT", label: "Austria", deprecated: false},
    %{value: "AZE", label: "Azerbaiyán", deprecated: false},
    %{value: "BHS", label: "Bahamas (las)", deprecated: false},
    %{value: "BGD", label: "Bangladés", deprecated: false},
    %{value: "BRB", label: "Barbados", deprecated: false},
    %{value: "BHR", label: "Baréin", deprecated: false},
    %{value: "BEL", label: "Bélgica", deprecated: false},
    %{value: "BLZ", label: "Belice", deprecated: false},
    %{value: "BEN", label: "Benín", deprecated: false},
    %{value: "BMU", label: "Bermudas", deprecated: false},
    %{value: "BLR", label: "Bielorrusia", deprecated: false},
    %{value: "MMR", label: "Myanmar", deprecated: false},
    %{value: "BOL", label: "Bolivia, Estado Plurinacional de", deprecated: false},
    %{value: "BIH", label: "Bosnia y Herzegovina", deprecated: false},
    %{value: "BWA", label: "Botsuana", deprecated: false},
    %{value: "BRA", label: "Brasil", deprecated: false},
    %{value: "BRN", label: "Brunéi Darussalam", deprecated: false},
    %{value: "BGR", label: "Bulgaria", deprecated: false},
    %{value: "BFA", label: "Burkina Faso", deprecated: false},
    %{value: "BDI", label: "Burundi", deprecated: false},
    %{value: "BTN", label: "Bután", deprecated: false},
    %{value: "CPV", label: "Cabo Verde", deprecated: false},
    %{value: "KHM", label: "Camboya", deprecated: false},
    %{value: "CMR", label: "Camerún", deprecated: false},
    %{value: "CAN", label: "Canadá", deprecated: false},
    %{value: "QAT", label: "Catar", deprecated: false},
    %{value: "BES", label: "Bonaire, San Eustaquio y Saba", deprecated: false},
    %{value: "TCD", label: "Chad", deprecated: false},
    %{value: "CHL", label: "Chile", deprecated: false},
    %{value: "CHN", label: "China", deprecated: false},
    %{value: "CYP", label: "Chipre", deprecated: false},
    %{value: "COL", label: "Colombia", deprecated: false},
    %{value: "COM", label: "Comoras", deprecated: false},
    %{value: "PRK", label: "Corea (la República Democrática Popular de)", deprecated: false},
    %{value: "KOR", label: "Corea (la República de)", deprecated: false},
    %{value: "CIV", label: "Côte d'Ivoire", deprecated: false},
    %{value: "CRI", label: "Costa Rica", deprecated: false},
    %{value: "HRV", label: "Croacia", deprecated: false},
    %{value: "CUB", label: "Cuba", deprecated: false},
    %{value: "CUW", label: "Curaçao", deprecated: false},
    %{value: "DNK", label: "Dinamarca", deprecated: false},
    %{value: "DMA", label: "Dominica", deprecated: false},
    %{value: "ECU", label: "Ecuador", deprecated: false},
    %{value: "EGY", label: "Egipto", deprecated: false},
    %{value: "SLV", label: "El Salvador", deprecated: false},
    %{value: "ARE", label: "Emiratos Árabes Unidos (Los)", deprecated: false},
    %{value: "ERI", label: "Eritrea", deprecated: false},
    %{value: "SVK", label: "Eslovaquia", deprecated: false},
    %{value: "SVN", label: "Eslovenia", deprecated: false},
    %{value: "ESP", label: "España", deprecated: false},
    %{value: "USA", label: "Estados Unidos (los)", deprecated: false},
    %{value: "EST", label: "Estonia", deprecated: false},
    %{value: "ETH", label: "Etiopía", deprecated: false},
    %{value: "PHL", label: "Filipinas (las)", deprecated: false},
    %{value: "FIN", label: "Finlandia", deprecated: false},
    %{value: "FJI", label: "Fiyi", deprecated: false},
    %{value: "FRA", label: "Francia", deprecated: false},
    %{value: "GAB", label: "Gabón", deprecated: false},
    %{value: "GMB", label: "Gambia (La)", deprecated: false},
    %{value: "GEO", label: "Georgia", deprecated: false},
    %{value: "GHA", label: "Ghana", deprecated: false},
    %{value: "GIB", label: "Gibraltar", deprecated: false},
    %{value: "GRD", label: "Granada", deprecated: false},
    %{value: "GRC", label: "Grecia", deprecated: false},
    %{value: "GRL", label: "Groenlandia", deprecated: false},
    %{value: "GLP", label: "Guadalupe", deprecated: false},
    %{value: "GUM", label: "Guam", deprecated: false},
    %{value: "GTM", label: "Guatemala", deprecated: false},
    %{value: "GUF", label: "Guayana Francesa", deprecated: false},
    %{value: "GGY", label: "Guernsey", deprecated: false},
    %{value: "GIN", label: "Guinea", deprecated: false},
    %{value: "GNB", label: "Guinea-Bisáu", deprecated: false},
    %{value: "GNQ", label: "Guinea Ecuatorial", deprecated: false},
    %{value: "GUY", label: "Guyana", deprecated: false},
    %{value: "HTI", label: "Haití", deprecated: false},
    %{value: "HND", label: "Honduras", deprecated: false},
    %{value: "HKG", label: "Hong Kong", deprecated: false},
    %{value: "HUN", label: "Hungría", deprecated: false},
    %{value: "IND", label: "India", deprecated: false},
    %{value: "IDN", label: "Indonesia", deprecated: false},
    %{value: "IRQ", label: "Irak", deprecated: false},
    %{value: "IRN", label: "Irán (la República Islámica de)", deprecated: false},
    %{value: "IRL", label: "Irlanda", deprecated: false},
    %{value: "BVT", label: "Isla Bouvet", deprecated: false},
    %{value: "IMN", label: "Isla de Man", deprecated: false},
    %{value: "CXR", label: "Isla de Navidad", deprecated: false},
    %{value: "NFK", label: "Isla Norfolk", deprecated: false},
    %{value: "ISL", label: "Islandia", deprecated: false},
    %{value: "CYM", label: "Islas Caimán (las)", deprecated: false},
    %{value: "CCK", label: "Islas Cocos (Keeling)", deprecated: false},
    %{value: "COK", label: "Islas Cook (las)", deprecated: false},
    %{value: "FRO", label: "Islas Feroe (las)", deprecated: false},
    %{value: "SGS", label: "Georgia del sur y las islas sandwich del sur", deprecated: false},
    %{value: "HMD", label: "Isla Heard e Islas McDonald", deprecated: false},
    %{value: "FLK", label: "Islas Malvinas [Falkland] (las)", deprecated: false},
    %{value: "MNP", label: "Islas Marianas del Norte (las)", deprecated: false},
    %{value: "MHL", label: "Islas Marshall (las)", deprecated: false},
    %{value: "PCN", label: "Pitcairn", deprecated: false},
    %{value: "SLB", label: "Islas Salomón (las)", deprecated: false},
    %{value: "TCA", label: "Islas Turcas y Caicos (las)", deprecated: false},
    %{
      value: "UMI",
      label: "Islas de Ultramar Menores de Estados Unidos (las)",
      deprecated: false
    },
    %{value: "VGB", label: "Islas Vírgenes (Británicas)", deprecated: false},
    %{value: "VIR", label: "Islas Vírgenes (EE.UU.)", deprecated: false},
    %{value: "ISR", label: "Israel", deprecated: false},
    %{value: "ITA", label: "Italia", deprecated: false},
    %{value: "JAM", label: "Jamaica", deprecated: false},
    %{value: "JPN", label: "Japón", deprecated: false},
    %{value: "JEY", label: "Jersey", deprecated: false},
    %{value: "JOR", label: "Jordania", deprecated: false},
    %{value: "KAZ", label: "Kazajistán", deprecated: false},
    %{value: "KEN", label: "Kenia", deprecated: false},
    %{value: "KGZ", label: "Kirguistán", deprecated: false},
    %{value: "KIR", label: "Kiribati", deprecated: false},
    %{value: "KWT", label: "Kuwait", deprecated: false},
    %{value: "LAO", label: "Lao, (la) República Democrática Popular", deprecated: false},
    %{value: "LSO", label: "Lesoto", deprecated: false},
    %{value: "LVA", label: "Letonia", deprecated: false},
    %{value: "LBN", label: "Líbano", deprecated: false},
    %{value: "LBR", label: "Liberia", deprecated: false},
    %{value: "LBY", label: "Libia", deprecated: false},
    %{value: "LIE", label: "Liechtenstein", deprecated: false},
    %{value: "LTU", label: "Lituania", deprecated: false},
    %{value: "LUX", label: "Luxemburgo", deprecated: false},
    %{value: "MAC", label: "Macao", deprecated: false},
    %{value: "MDG", label: "Madagascar", deprecated: false},
    %{value: "MYS", label: "Malasia", deprecated: false},
    %{value: "MWI", label: "Malaui", deprecated: false},
    %{value: "MDV", label: "Maldivas", deprecated: false},
    %{value: "MLI", label: "Malí", deprecated: false},
    %{value: "MLT", label: "Malta", deprecated: false},
    %{value: "MAR", label: "Marruecos", deprecated: false},
    %{value: "MTQ", label: "Martinica", deprecated: false},
    %{value: "MUS", label: "Mauricio", deprecated: false},
    %{value: "MRT", label: "Mauritania", deprecated: false},
    %{value: "MYT", label: "Mayotte", deprecated: false},
    %{value: "MEX", label: "México", deprecated: false},
    %{value: "FSM", label: "Micronesia (los Estados Federados de)", deprecated: false},
    %{value: "MDA", label: "Moldavia (la República de)", deprecated: false},
    %{value: "MCO", label: "Mónaco", deprecated: false},
    %{value: "MNG", label: "Mongolia", deprecated: false},
    %{value: "MNE", label: "Montenegro", deprecated: false},
    %{value: "MSR", label: "Montserrat", deprecated: false},
    %{value: "MOZ", label: "Mozambique", deprecated: false},
    %{value: "NAM", label: "Namibia", deprecated: false},
    %{value: "NRU", label: "Nauru", deprecated: false},
    %{value: "NPL", label: "Nepal", deprecated: false},
    %{value: "NIC", label: "Nicaragua", deprecated: false},
    %{value: "NER", label: "Níger (el)", deprecated: false},
    %{value: "NGA", label: "Nigeria", deprecated: false},
    %{value: "NIU", label: "Niue", deprecated: false},
    %{value: "NOR", label: "Noruega", deprecated: false},
    %{value: "NCL", label: "Nueva Caledonia", deprecated: false},
    %{value: "NZL", label: "Nueva Zelanda", deprecated: false},
    %{value: "OMN", label: "Omán", deprecated: false},
    %{value: "NLD", label: "Países Bajos (los)", deprecated: false},
    %{value: "PAK", label: "Pakistán", deprecated: false},
    %{value: "PLW", label: "Palaos", deprecated: false},
    %{value: "PSE", label: "Palestina, Estado de", deprecated: false},
    %{value: "PAN", label: "Panamá", deprecated: false},
    %{value: "PNG", label: "Papúa Nueva Guinea", deprecated: false},
    %{value: "PRY", label: "Paraguay", deprecated: false},
    %{value: "PER", label: "Perú", deprecated: false},
    %{value: "PYF", label: "Polinesia Francesa", deprecated: false},
    %{value: "POL", label: "Polonia", deprecated: false},
    %{value: "PRT", label: "Portugal", deprecated: false},
    %{value: "PRI", label: "Puerto Rico", deprecated: false},
    %{value: "GBR", label: "Reino Unido (el)", deprecated: false},
    %{value: "CAF", label: "República Centroafricana (la)", deprecated: false},
    %{value: "CZE", label: "República Checa (la)", deprecated: false},
    %{value: "MKD", label: "Macedonia (la antigua República Yugoslava de)", deprecated: false},
    %{value: "COG", label: "Congo", deprecated: false},
    %{value: "COD", label: "Congo (la República Democrática del)", deprecated: false},
    %{value: "DOM", label: "República Dominicana (la)", deprecated: false},
    %{value: "REU", label: "Reunión", deprecated: false},
    %{value: "RWA", label: "Ruanda", deprecated: false},
    %{value: "ROU", label: "Rumania", deprecated: false},
    %{value: "RUS", label: "Rusia, (la) Federación de", deprecated: false},
    %{value: "ESH", label: "Sahara Occidental", deprecated: false},
    %{value: "WSM", label: "Samoa", deprecated: false},
    %{value: "ASM", label: "Samoa Americana", deprecated: false},
    %{value: "BLM", label: "San Bartolomé", deprecated: false},
    %{value: "KNA", label: "San Cristóbal y Nieves", deprecated: false},
    %{value: "SMR", label: "San Marino", deprecated: false},
    %{value: "MAF", label: "San Martín (parte francesa)", deprecated: false},
    %{value: "SPM", label: "San Pedro y Miquelón", deprecated: false},
    %{value: "VCT", label: "San Vicente y las Granadinas", deprecated: false},
    %{value: "SHN", label: "Santa Helena, Ascensión y Tristán de Acuña", deprecated: false},
    %{value: "LCA", label: "Santa Lucía", deprecated: false},
    %{value: "STP", label: "Santo Tomé y Príncipe", deprecated: false},
    %{value: "SEN", label: "Senegal", deprecated: false},
    %{value: "SRB", label: "Serbia", deprecated: false},
    %{value: "SYC", label: "Seychelles", deprecated: false},
    %{value: "SLE", label: "Sierra leona", deprecated: false},
    %{value: "SGP", label: "Singapur", deprecated: false},
    %{value: "SXM", label: "Sint Maarten (parte holandesa)", deprecated: false},
    %{value: "SYR", label: "Siria, (la) República Árabe", deprecated: false},
    %{value: "SOM", label: "Somalia", deprecated: false},
    %{value: "LKA", label: "Sri Lanka", deprecated: false},
    %{value: "SWZ", label: "Suazilandia", deprecated: false},
    %{value: "ZAF", label: "Sudáfrica", deprecated: false},
    %{value: "SDN", label: "Sudán (el)", deprecated: false},
    %{value: "SSD", label: "Sudán del Sur", deprecated: false},
    %{value: "SWE", label: "Suecia", deprecated: false},
    %{value: "CHE", label: "Suiza", deprecated: false},
    %{value: "SUR", label: "Surinam", deprecated: false},
    %{value: "SJM", label: "Svalbard y Jan Mayen", deprecated: false},
    %{value: "THA", label: "Tailandia", deprecated: false},
    %{value: "TWN", label: "Taiwán (Provincia de China)", deprecated: false},
    %{value: "TZA", label: "Tanzania, República Unida de", deprecated: false},
    %{value: "TJK", label: "Tayikistán", deprecated: false},
    %{value: "IOT", label: "Territorio Británico del Océano Índico (el)", deprecated: false},
    %{value: "ATF", label: "Territorios Australes Franceses (los)", deprecated: false},
    %{value: "TLS", label: "Timor-Leste", deprecated: false},
    %{value: "TGO", label: "Togo", deprecated: false},
    %{value: "TKL", label: "Tokelau", deprecated: false},
    %{value: "TON", label: "Tonga", deprecated: false},
    %{value: "TTO", label: "Trinidad y Tobago", deprecated: false},
    %{value: "TUN", label: "Túnez", deprecated: false},
    %{value: "TKM", label: "Turkmenistán", deprecated: false},
    %{value: "TUR", label: "Turquía", deprecated: false},
    %{value: "TUV", label: "Tuvalu", deprecated: false},
    %{value: "UKR", label: "Ucrania", deprecated: false},
    %{value: "UGA", label: "Uganda", deprecated: false},
    %{value: "URY", label: "Uruguay", deprecated: false},
    %{value: "UZB", label: "Uzbekistán", deprecated: false},
    %{value: "VUT", label: "Vanuatu", deprecated: false},
    %{
      value: "VAT",
      label: "Santa Sede[Estado de la Ciudad del Vaticano] (la)",
      deprecated: false
    },
    %{value: "VEN", label: "Venezuela, República Bolivariana de", deprecated: false},
    %{value: "VNM", label: "Viet Nam", deprecated: false},
    %{value: "WLF", label: "Wallis y Futuna", deprecated: false},
    %{value: "YEM", label: "Yemen", deprecated: false},
    %{value: "DJI", label: "Yibuti", deprecated: false},
    %{value: "ZMB", label: "Zambia", deprecated: false},
    %{value: "ZWE", label: "Zimbabue", deprecated: false},
    %{value: "ZZZ", label: "Países no declarados", deprecated: false}
  ]

  @doc "Lista completa del catálogo."
  def list, do: @entries

  @doc "Devuelve true si el código existe en el catálogo."
  def valid?(code) when is_binary(code), do: Enum.any?(@entries, &(&1.value == code))
  def valid?(_), do: false

  @doc "Busca una entrada por su código."
  def from_code(code) when is_binary(code) do
    case Enum.find(@entries, &(&1.value == code)) do
      nil -> :error
      entry -> {:ok, entry}
    end
  end
end
